185/Connect_youtube
dashdash/integration-youtube pull request #1
Opened 2020-12-04 16:03 UTC by farouqBenarous

# Connect to Youtube #184

## Issue(s) Reference:
- Github card  https://github.com/dashdash/integrator/issues/184

2020-12-04 16:15 UTC, DBastos-mindera requested changes

2020-12-04 16:15 UTC, DBastos-mindera commented on pom.xml
> +    <version>0.0.1</version>
Should be a SNAPSHOT version, right?

2020-12-04 16:17 UTC, farouqBenarous commented on pom.xml
> +    <version>0.0.1</version>
Yeap true

2020-12-04 17:39 UTC, gustavocortarelli commented on pom.xml
> +
there is a different structure that should be used on pom files that makes this file simpler. Check the facebookads as example

2020-12-04 17:47 UTC, farouqBenarous commented on pom.xml
> +
Yes this file was generate by new.  archtype

2020-12-04 18:23 UTC, gustavocortarelli approved these changes

2020-12-09 10:24 UTC, DBastos-mindera approved these changes

2020-12-09 10:28 UTC, merged